spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  application:
    name: users
  datasource:
    url: jdbc:postgresql://localhost:37012/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

auth:
  app:
    jwtSecret: Y294cGxleC1zZWN1cmUtcmFfZG9TLXN0cmluZy1rZXkzMjM0NTY
    jwtExpirationMs: 1209600000

server:
  port: 37002

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method