spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  application:
    name: users
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_LOGIN}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
auth:
  app:
    jwtSecret: Y294cGxleC1zZWN1cmUtcmFfZG9TLXN0cmluZy1rZXkzMjM0NTY
    jwtExpirationMs: 1209600000
server:
  port: ${APP_PORT}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method